// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrganizationalSingularity.Infrastructure.Persistence;

#nullable disable

namespace OrganizationalSingularity.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260812165849_AddIntelligenceDebtCategoryMapping")]
    partial class AddIntelligenceDebtCategoryMapping
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrganizationalSingularity.Domain.Assessments.Assessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FrameworkVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SupersedesAssessmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FrameworkVersionId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("SupersedesAssessmentId");

                    b.HasIndex("TenantId");

                    b.ToTable("Assessments");
                });

            modelBuilder.Entity("OrganizationalSingularity.Domain.Assessments.AssessmentResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AnswerState")
                        .HasColumnType("integer");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Confidence")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string[]>("EvidenceReferences")
                        .HasColumnType("text[]");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("RespondentComment")
                        .HasColumnType("text");

                    b.Property<Guid?>("ReviewedMaturityLevelId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReviewerComment")
                        .HasColumnType("text");

                    b.Property<Guid?>("SelectedMaturityLevelId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("ReviewedMaturityLevelId");

                    b.HasIndex("SelectedMaturityLevelId");

                    b.HasIndex("TenantId");

                    b.HasIndex("AssessmentId", "QuestionId")
                        .IsUnique();

                    b.ToTable("AssessmentResponses");
                });

            modelBuilder.Entity("OrganizationalSingularity.Domain.Assessments.AssessmentResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CalculatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("CompositeAverage")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentId")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("AssessmentResults");
                });

            modelBuilder.Entity("OrganizationalSingularity.Domain.Assessments.CapabilityScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AnsweredQuestionCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("AssessmentResultId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CapabilityId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Score")
                        .HasColumnType("numeric");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CapabilityId");

                    b.HasIndex("TenantId");

                    b.HasIndex("AssessmentResultId", "CapabilityId")
                        .IsUnique();

                    b.ToTable("CapabilityScores");
                });

            modelBuilder.Entity("OrganizationalSingularity.Domain.Assessments.DimensionScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssessmentResultId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DimensionId")
                        .HasColumnType("uuid");

                    b.Property<string>("MaturityBand")
                        .HasColumnType("text");

                    b.Property<decimal?>("Score")
                        .HasColumnType("numeric");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DimensionId");

                    b.HasIndex("TenantId");

                    b.HasIndex("AssessmentResultId", "DimensionId")
                        .IsUnique();

                    b.ToTable("DimensionScores");
                });

            modelBuilder.Entity("OrganizationalSingularity.Domain.Audit.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditEvents");
                });

            modelBuilder.Entity("OrganizationalSingularity.Domain.Framework.AssessmentQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CapabilityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CapabilityId", "Code")
                        .IsUnique();

                    b.ToTable("AssessmentQuestions");
                });

            modelBuilder.Entity("OrganizationalSingularity.Domain.Framework.Capability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("DimensionId")
                        .HasColumnType("uuid");

                    b.Property<string>("EvidenceGuidance")
                        .HasColumnType("text");

                    b.Property<Guid>("FrameworkVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DimensionId");

                    b.HasIndex("FrameworkVersionId", "Code")
                        .IsUnique();

                    b.ToTable("Capabilities");
                });

            modelBuilder.Entity("OrganizationalSingularity.Domain.Framework.Dimension", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FrameworkVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("FundamentalQuestion")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FrameworkVersionId", "Code")
                        .IsUnique();

                    b.ToTable("Dimensions");
                });

            modelBuilder.Entity("OrganizationalSingularity.Domain.Framework.FrameworkVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Version")
                        .IsUnique();

                    b.ToTable("FrameworkVersions");
                });

            modelBuilder.Entity("OrganizationalSingularity.Domain.Framework.MaturityBand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FrameworkVersionId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MaxScore")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MinScore")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FrameworkVersionId", "Name")
                        .IsUnique();

                    b.ToTable("MaturityBands");
                });

            modelBuilder.Entity("OrganizationalSingularity.Domain.Framework.MaturityLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("FrameworkVersionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FrameworkVersionId", "Level")
                        .IsUnique();

                    b.ToTable("MaturityLevels");
                });

            modelBuilder.Entity("OrganizationalSingularity.Domain.Identity.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("InvitedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique()
                        .HasFilter("\"ConsumedAtUtc\" IS NULL");

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("OrganizationalSingularity.Domain.Identity.Membership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AcceptedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("InvitedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.HasIndex("TenantId", "UserId")
                        .IsUnique();

                    b.ToTable("Memberships");
                });

            modelBuilder.Entity("OrganizationalSingularity.Domain.Identity.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TenantModel")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("OrganizationalSingularity.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntraObjectId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EntraObjectId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OrganizationalSingularity.Domain.IntelligenceDebt.IntelligenceDebtCategoryMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DimensionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FrameworkVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DimensionId");

                    b.HasIndex("FrameworkVersionId", "DimensionId")
                        .IsUnique();

                    b.ToTable("IntelligenceDebtCategoryMappings");
                });

            modelBuilder.Entity("OrganizationalSingularity.Domain.IntelligenceDebt.IntelligenceDebtDependency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DependsOnFindingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FindingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DependsOnFindingId");

                    b.HasIndex("TenantId");

                    b.HasIndex("FindingId", "DependsOnFindingId")
                        .IsUnique();

                    b.ToTable("IntelligenceDebtDependencies");
                });

            modelBuilder.Entity("OrganizationalSingularity.Domain.IntelligenceDebt.IntelligenceDebtEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AddedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssessmentResponseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<int>("EvidenceType")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalUri")
                        .HasColumnType("text");

                    b.Property<Guid>("FindingId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceReference")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AddedByUserId");

                    b.HasIndex("AssessmentResponseId");

                    b.HasIndex("FindingId");

                    b.HasIndex("TenantId");

                    b.ToTable("IntelligenceDebtEvidence");
                });

            modelBuilder.Entity("OrganizationalSingularity.Domain.IntelligenceDebt.IntelligenceDebtFinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AffectedScope")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ApprovedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssessmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("BusinessImpact")
                        .HasColumnType("text");

                    b.Property<Guid?>("CapabilityId")
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DetectionSource")
                        .HasColumnType("integer");

                    b.Property<Guid?>("DimensionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Outcome")
                        .HasColumnType("text");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("RecommendedAction")
                        .HasColumnType("text");

                    b.Property<string>("RemediationPlan")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("RemediationStartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("TargetResolutionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ValidatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ValidatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ValidationCriteria")
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("CapabilityId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DimensionId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("TenantId");

                    b.HasIndex("ValidatedByUserId");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique();

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("IntelligenceDebtFindings");
                });

            modelBuilder.Entity("OrganizationalSingularity.Domain.Organizations.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EmployeeCount")
                        .HasColumnType("integer");

                    b.Property<string>("Industry")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("OrganizationalSingularity.Domain.Assessments.Assessment", b =>
                {
                    b.HasOne("OrganizationalSingularity.Domain.Framework.FrameworkVersion", "FrameworkVersion")
                        .WithMany()
                        .HasForeignKey("FrameworkVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrganizationalSingularity.Domain.Organizations.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrganizationalSingularity.Domain.Assessments.Assessment", "SupersedesAssessment")
                        .WithMany()
                        .HasForeignKey("SupersedesAssessmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FrameworkVersion");

                    b.Navigation("Organization");

                    b.Navigation("SupersedesAssessment");
                });

            modelBuilder.Entity("OrganizationalSingularity.Domain.Assessments.AssessmentResponse", b =>
                {
                    b.HasOne("OrganizationalSingularity.Domain.Assessments.Assessment", "Assessment")
                        .WithMany("Responses")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrganizationalSingularity.Domain.Framework.AssessmentQuestion", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrganizationalSingularity.Domain.Framework.MaturityLevel", "ReviewedMaturityLevel")
                        .WithMany()
                        .HasForeignKey("ReviewedMaturityLevelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OrganizationalSingularity.Domain.Framework.MaturityLevel", "SelectedMaturityLevel")
                        .WithMany()
                        .HasForeignKey("SelectedMaturityLevelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Assessment");

                    b.Navigation("Question");

                    b.Navigation("ReviewedMaturityLevel");

                    b.Navigation("SelectedMaturityLevel");
                });

            modelBuilder.Entity("OrganizationalSingularity.Domain.Assessments.AssessmentResult", b =>
                {
                    b.HasOne("OrganizationalSingularity.Domain.Assessments.Assessment", "Assessment")
                        .WithOne("Result")
                        .HasForeignKey("OrganizationalSingularity.Domain.Assessments.AssessmentResult", "AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assessment");
                });

            modelBuilder.Entity("OrganizationalSingularity.Domain.Assessments.CapabilityScore", b =>
                {
                    b.HasOne("OrganizationalSingularity.Domain.Assessments.AssessmentResult", "AssessmentResult")
                        .WithMany("CapabilityScores")
                        .HasForeignKey("AssessmentResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrganizationalSingularity.Domain.Framework.Capability", "Capability")
                        .WithMany()
                        .HasForeignKey("CapabilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssessmentResult");

                    b.Navigation("Capability");
                });

            modelBuilder.Entity("OrganizationalSingularity.Domain.Assessments.DimensionScore", b =>
                {
                    b.HasOne("OrganizationalSingularity.Domain.Assessments.AssessmentResult", "AssessmentResult")
                        .WithMany("DimensionScores")
                        .HasForeignKey("AssessmentResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrganizationalSingularity.Domain.Framework.Dimension", "Dimension")
                        .WithMany()
                        .HasForeignKey("DimensionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssessmentResult");

                    b.Navigation("Dimension");
                });

            modelBuilder.Entity("OrganizationalSingularity.Domain.Framework.AssessmentQuestion", b =>
                {
                    b.HasOne("OrganizationalSingularity.Domain.Framework.Capability", "Capability")
                        .WithMany("Questions")
                        .HasForeignKey("CapabilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("OrganizationalSingularity.Domain.Framework.Provenance", "Provenance", b1 =>
                        {
                            b1.Property<Guid>("AssessmentQuestionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("MethodologyStatus")
                                .HasColumnType("text");

                            b1.Property<int>("SourceClassification")
                                .HasColumnType("integer");

                            b1.Property<string>("SourceDocument")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("SourceSection")
                                .HasColumnType("text");

                            b1.HasKey("AssessmentQuestionId");

                            b1.ToTable("AssessmentQuestions");

                            b1.WithOwner()
                                .HasForeignKey("AssessmentQuestionId");
                        });

                    b.Navigation("Capability");

                    b.Navigation("Provenance")
                        .IsRequired();
                });

            modelBuilder.Entity("OrganizationalSingularity.Domain.Framework.Capability", b =>
                {
                    b.HasOne("OrganizationalSingularity.Domain.Framework.Dimension", "Dimension")
                        .WithMany("Capabilities")
                        .HasForeignKey("DimensionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrganizationalSingularity.Domain.Framework.FrameworkVersion", "FrameworkVersion")
                        .WithMany("Capabilities")
                        .HasForeignKey("FrameworkVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("OrganizationalSingularity.Domain.Framework.Provenance", "Provenance", b1 =>
                        {
                            b1.Property<Guid>("CapabilityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("MethodologyStatus")
                                .HasColumnType("text");

                            b1.Property<int>("SourceClassification")
                                .HasColumnType("integer");

                            b1.Property<string>("SourceDocument")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("SourceSection")
                                .HasColumnType("text");

                            b1.HasKey("CapabilityId");

                            b1.ToTable("Capabilities");

                            b1.WithOwner()
                                .HasForeignKey("CapabilityId");
                        });

                    b.Navigation("Dimension");

                    b.Navigation("FrameworkVersion");

                    b.Navigation("Provenance")
                        .IsRequired();
                });

            modelBuilder.Entity("OrganizationalSingularity.Domain.Framework.Dimension", b =>
                {
                    b.HasOne("OrganizationalSingularity.Domain.Framework.FrameworkVersion", "FrameworkVersion")
                        .WithMany()
                        .HasForeignKey("FrameworkVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("OrganizationalSingularity.Domain.Framework.Provenance", "Provenance", b1 =>
                        {
                            b1.Property<Guid>("DimensionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("MethodologyStatus")
                                .HasColumnType("text");

                            b1.Property<int>("SourceClassification")
                                .HasColumnType("integer");

                            b1.Property<string>("SourceDocument")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("SourceSection")
                                .HasColumnType("text");

                            b1.HasKey("DimensionId");

                            b1.ToTable("Dimensions");

                            b1.WithOwner()
                                .HasForeignKey("DimensionId");
                        });

                    b.Navigation("FrameworkVersion");

                    b.Navigation("Provenance")
                        .IsRequired();
                });

            modelBuilder.Entity("OrganizationalSingularity.Domain.Framework.MaturityBand", b =>
                {
                    b.HasOne("OrganizationalSingularity.Domain.Framework.FrameworkVersion", "FrameworkVersion")
                        .WithMany()
                        .HasForeignKey("FrameworkVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("OrganizationalSingularity.Domain.Framework.Provenance", "Provenance", b1 =>
                        {
                            b1.Property<Guid>("MaturityBandId")
                                .HasColumnType("uuid");

                            b1.Property<string>("MethodologyStatus")
                                .HasColumnType("text");

                            b1.Property<int>("SourceClassification")
                                .HasColumnType("integer");

                            b1.Property<string>("SourceDocument")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("SourceSection")
                                .HasColumnType("text");

                            b1.HasKey("MaturityBandId");

                            b1.ToTable("MaturityBands");

                            b1.WithOwner()
                                .HasForeignKey("MaturityBandId");
                        });

                    b.Navigation("FrameworkVersion");

                    b.Navigation("Provenance")
                        .IsRequired();
                });

            modelBuilder.Entity("OrganizationalSingularity.Domain.Framework.MaturityLevel", b =>
                {
                    b.HasOne("OrganizationalSingularity.Domain.Framework.FrameworkVersion", "FrameworkVersion")
                        .WithMany("MaturityLevels")
                        .HasForeignKey("FrameworkVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("OrganizationalSingularity.Domain.Framework.Provenance", "Provenance", b1 =>
                        {
                            b1.Property<Guid>("MaturityLevelId")
                                .HasColumnType("uuid");

                            b1.Property<string>("MethodologyStatus")
                                .HasColumnType("text");

                            b1.Property<int>("SourceClassification")
                                .HasColumnType("integer");

                            b1.Property<string>("SourceDocument")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("SourceSection")
                                .HasColumnType("text");

                            b1.HasKey("MaturityLevelId");

                            b1.ToTable("MaturityLevels");

                            b1.WithOwner()
                                .HasForeignKey("MaturityLevelId");
                        });

                    b.Navigation("FrameworkVersion");

                    b.Navigation("Provenance")
                        .IsRequired();
                });

            modelBuilder.Entity("OrganizationalSingularity.Domain.Identity.Membership", b =>
                {
                    b.HasOne("OrganizationalSingularity.Domain.Identity.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrganizationalSingularity.Domain.Identity.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrganizationalSingularity.Domain.IntelligenceDebt.IntelligenceDebtCategoryMapping", b =>
                {
                    b.HasOne("OrganizationalSingularity.Domain.Framework.Dimension", "Dimension")
                        .WithMany()
                        .HasForeignKey("DimensionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrganizationalSingularity.Domain.Framework.FrameworkVersion", "FrameworkVersion")
                        .WithMany()
                        .HasForeignKey("FrameworkVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("OrganizationalSingularity.Domain.Framework.Provenance", "Provenance", b1 =>
                        {
                            b1.Property<Guid>("IntelligenceDebtCategoryMappingId")
                                .HasColumnType("uuid");

                            b1.Property<string>("MethodologyStatus")
                                .HasColumnType("text");

                            b1.Property<int>("SourceClassification")
                                .HasColumnType("integer");

                            b1.Property<string>("SourceDocument")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("SourceSection")
                                .HasColumnType("text");

                            b1.HasKey("IntelligenceDebtCategoryMappingId");

                            b1.ToTable("IntelligenceDebtCategoryMappings");

                            b1.WithOwner()
                                .HasForeignKey("IntelligenceDebtCategoryMappingId");
                        });

                    b.Navigation("Dimension");

                    b.Navigation("FrameworkVersion");

                    b.Navigation("Provenance")
                        .IsRequired();
                });

            modelBuilder.Entity("OrganizationalSingularity.Domain.IntelligenceDebt.IntelligenceDebtDependency", b =>
                {
                    b.HasOne("OrganizationalSingularity.Domain.IntelligenceDebt.IntelligenceDebtFinding", "DependsOnFinding")
                        .WithMany()
                        .HasForeignKey("DependsOnFindingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrganizationalSingularity.Domain.IntelligenceDebt.IntelligenceDebtFinding", "Finding")
                        .WithMany()
                        .HasForeignKey("FindingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DependsOnFinding");

                    b.Navigation("Finding");
                });

            modelBuilder.Entity("OrganizationalSingularity.Domain.IntelligenceDebt.IntelligenceDebtEvidence", b =>
                {
                    b.HasOne("OrganizationalSingularity.Domain.Identity.User", "AddedByUser")
                        .WithMany()
                        .HasForeignKey("AddedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrganizationalSingularity.Domain.Assessments.AssessmentResponse", "AssessmentResponse")
                        .WithMany()
                        .HasForeignKey("AssessmentResponseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OrganizationalSingularity.Domain.IntelligenceDebt.IntelligenceDebtFinding", "Finding")
                        .WithMany("Evidence")
                        .HasForeignKey("FindingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddedByUser");

                    b.Navigation("AssessmentResponse");

                    b.Navigation("Finding");
                });

            modelBuilder.Entity("OrganizationalSingularity.Domain.IntelligenceDebt.IntelligenceDebtFinding", b =>
                {
                    b.HasOne("OrganizationalSingularity.Domain.Identity.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OrganizationalSingularity.Domain.Assessments.Assessment", "Assessment")
                        .WithMany()
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OrganizationalSingularity.Domain.Framework.Capability", "Capability")
                        .WithMany()
                        .HasForeignKey("CapabilityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OrganizationalSingularity.Domain.Identity.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrganizationalSingularity.Domain.Framework.Dimension", "Dimension")
                        .WithMany()
                        .HasForeignKey("DimensionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OrganizationalSingularity.Domain.Organizations.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrganizationalSingularity.Domain.Identity.User", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OrganizationalSingularity.Domain.Identity.User", "ValidatedByUser")
                        .WithMany()
                        .HasForeignKey("ValidatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApprovedByUser");

                    b.Navigation("Assessment");

                    b.Navigation("Capability");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Dimension");

                    b.Navigation("Organization");

                    b.Navigation("OwnerUser");

                    b.Navigation("ValidatedByUser");
                });

            modelBuilder.Entity("OrganizationalSingularity.Domain.Assessments.Assessment", b =>
                {
                    b.Navigation("Responses");

                    b.Navigation("Result");
                });

            modelBuilder.Entity("OrganizationalSingularity.Domain.Assessments.AssessmentResult", b =>
                {
                    b.Navigation("CapabilityScores");

                    b.Navigation("DimensionScores");
                });

            modelBuilder.Entity("OrganizationalSingularity.Domain.Framework.Capability", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("OrganizationalSingularity.Domain.Framework.Dimension", b =>
                {
                    b.Navigation("Capabilities");
                });

            modelBuilder.Entity("OrganizationalSingularity.Domain.Framework.FrameworkVersion", b =>
                {
                    b.Navigation("Capabilities");

                    b.Navigation("MaturityLevels");
                });

            modelBuilder.Entity("OrganizationalSingularity.Domain.Identity.User", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("OrganizationalSingularity.Domain.IntelligenceDebt.IntelligenceDebtFinding", b =>
                {
                    b.Navigation("Evidence");
                });
#pragma warning restore 612, 618
        }
    }
}
